apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-okk3
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0100-tenant/ci10t-777-0100-app/devfile-sample-okk3@sha256:7a7ab83e6f0204a87d71a45d9637105178eb42ca1b7ed5782fc28def92fe67e8
        name: my-nodejs
        resources: {}
status: {}
